### ISSUE TITLE
TypeError when trying to create

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_LSM6DS#4]
See banner below for CP version and HW. All libraries from bundle release 2020-02-18.
```python
Adafruit CircuitPython 5.0.0-beta.5 on 2020-02-05; Adafruit CLUE nRF52840 Express with nRF52840
>>> import board
>>> import adafruit_lsm6ds
>>> lsm = adafruit_lsm6ds.LSM6DS33(board.I2C())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_lsm6ds.py", line 225, in __init__
  File "adafruit_lsm6ds.py", line 237, in reset
  File "adafruit_register/i2c_bit.py", line 70, in __set__
  File "adafruit_register/i2c_bit.py", line 70, in __set__
  File "adafruit_bus_device/i2c_device.py", line 99, in write
TypeError: can't convert NoneType to int
>>> 
```

**Comment by caternuson** [comment]
Real issue is probably here:
https://github.com/adafruit/Adafruit_CircuitPython_BusDevice/issues/44

**Comment by caternuson** [comment]
So sure that I'm going to close this and only re-open if needed.
